language: r
r: bioc-devel

cache: packages
bioc_required: true
bioc_use_devel: true

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_LIBS="http://cran.rstudio.com"

r_packages:
  - ggplot2

bioc_packages:
  - KEGGREST
  - KEGGgraph
  - BiocStyle

after_failure:
  - ./travis-tool.sh dump_logs
