language: r
cache: packages
r: bioc-release

addons:
  apt:
    packages:
      - libxml2-dev
      - openjdk-7-jdk

r_binary_packages:
  - ggplot2
  - visNetwork

bioc_packages:
  - KEGGREST
  - KEGGgraph
  - BiocStyle
  - paxtoolsr
  - RCy3
  
r_github_packages:
  - afukushima/MSEApdata

after_failure:
  - ./travis-tool.sh dump_logs
