language: r
cache: packages
r: bioc-release

addons:
  apt:
    packages:
      - libxml2-dev

r_binary_packages:
  - ggplot2
  - visNetwork

bioc_packages:
  - KEGGREST
  - KEGGgraph
  - BiocStyle
  
r_github_packages:
  - cytoscape/r2cytoscape

after_failure:
  - ./travis-tool.sh dump_logs
